### ISSUE TITLE
is the same as Aho-Corasick ?

### ISSUE THREAD

**Issue by loveJasmine** [alexeld/regex-trie#7]
BTW, is there is a python version?

**Comment by alexeld** [comment]
Hey!

I'm afraid regex-trie isn't the same as Aho-Corasick. AC is an algorithm for efficiently searching strings, while regex-trie is more of a regex "compressor". The output is just a JavaScript regex, and any string searching relies 100% on your JS regex engine.

As far as I know there isn't a Python version, but don't take my word for it – I'm out of touch with the Python, so maybe there is..! :-)

**Comment by loveJasmine** [comment]
Got it and thanks~
